name: gyro_car
description: A Flutter application to control a car using joystick controls.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0  # For Bluetooth connectivity
  wifi_scan: ^0.4.0+1  # Replacing wifi_iot with recommended package
  shared_preferences: ^2.2.2  # For saving settings
  provider: ^6.1.1  # For state management
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
